# Generated by Django 6.0.4 on 2026-07-01 14:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.PositiveSmallIntegerField()),
                ('duration', models.PositiveIntegerField(default=0, help_text='Minutes (movies only)')),
                ('type', models.CharField(choices=[('Movie', 'Movie'), ('Series', 'Series')], max_length=10)),
                ('age_rating', models.CharField(choices=[('G', 'G'), ('PG', 'PG'), ('PG-13', 'PG-13'), ('R', 'R'), ('TV-14', 'TV-14'), ('TV-MA', 'TV-MA')], max_length=10)),
                ('thumbnail_url', models.URLField(blank=True)),
                ('trailer_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'content',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'db_table': 'genres',
            },
        ),
        migrations.CreateModel(
            name='ContentGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.content')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.genre')),
            ],
            options={
                'db_table': 'content_genres',
                'unique_together': {('content', 'genre')},
            },
        ),
        migrations.AddField(
            model_name='content',
            name='genres',
            field=models.ManyToManyField(related_name='content', through='content.ContentGenre', to='content.genre'),
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(blank=True, max_length=255)),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seasons', to='content.content')),
            ],
            options={
                'db_table': 'seasons',
                'unique_together': {('content', 'season_number')},
            },
        ),
        migrations.CreateModel(
            name='Episode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('episode_number', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('duration', models.PositiveIntegerField(help_text='Minutes')),
                ('description', models.TextField(blank=True)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='content.season')),
            ],
            options={
                'db_table': 'episodes',
                'unique_together': {('season', 'episode_number')},
            },
        ),
    ]
